### PR TITLE
Adding commands for new users

### PR DESCRIPTION
**Pull request by r1ckr**
Adding "Realse_" to the download URL
Adding `-f ` on the `rm` command to ignore if the file doesn't exists.
Adding `mkdir -p  $HOME/.terraform.d/plugins/` in case the user has never installed a plugin
Changing `$HOME` by `~` to be consistent

### CODE REVIEW

**Review by yyyogev — CHANGES_REQUESTED** [review]
Thanks for pointing that out @r1ckr !
I updated the latest release tag to match the download URL, could you please edit that in your PR and I'll approve it?
Thanks!

**Comment by r1ckr** [comment]
Sure, will remove the Release_ then

**Comment by r1ckr** [comment]
that's applied now @yyyogev

**Review by yyyogev — APPROVED** [review]
Great stuff!

Thanks a lot!

**Pull request merged**
